name: Build & Deploy to IIS

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: self-hosted
    defaults:
      run:
        shell: powershell   # <--- dùng Windows PowerShell

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies & Build React
        run: |
          npm -v
          node -v
          npm ci
          npm run build

      - name: Deploy to IIS folder (into ...\build)
        shell: powershell
        run: |
          $src     = Join-Path $env:GITHUB_WORKSPACE 'build'     # build tạo bởi npm
          $dstRoot = 'C:\sites\myapp-fe'
          $dst     = Join-Path $dstRoot 'build'                  # thư mục IIS trỏ tới

          if (!(Test-Path $src)) { throw "Build folder not found: $src" }
          if (!(Test-Path $dstRoot)) { New-Item -ItemType Directory -Force -Path $dstRoot | Out-Null }
          if (!(Test-Path $dst))     { New-Item -ItemType Directory -Force -Path $dst     | Out-Null }

          # Xoá sạch bên trong thư mục build, giữ web.config nếu muốn
          Get-ChildItem $dst -Force | Where-Object { $_.Name -ne 'web.config' } |
            Remove-Item -Recurse -Force -ErrorAction SilentlyContinue

          # Copy nội dung build mới
          robocopy $src $dst /MIR /NFL /NDL /NJH /NJS /NP
          $code = $LASTEXITCODE
          if ($code -ge 8) { throw "Robocopy failed with exit code $code" }
          # Rất quan trọng: reset để GitHub không fail step vì mã 1/2/3
          $global:LASTEXITCODE = 0

          # Đặt web.config trong thư mục build (nếu có trong repo)
          $wc = Join-Path $env:GITHUB_WORKSPACE 'web.config'
          if (Test-Path $wc) { Copy-Item $wc (Join-Path $dst 'web.config') -Force }




      - name: Restart IIS AppPool
        run: |
          Import-Module WebAdministration
          $appPool = "myapp-fe"
          if (Test-Path IIS:\AppPools\$appPool) { Restart-WebAppPool $appPool } else { IISReset /restart }
